apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.annotations.ingressClass}}
    # cert-manager.io/issue-temporary-certificate: "true"
    # cert-manager.io/cluster-issuer: letsencrypt
  labels:
    name: {{ .Values.ingress.labels.name }}
spec:
  rules:
  - host: {{ .Values.ingress.hosts.host }}
    http:
      paths:
      - pathType: {{ .Values.ingress.hosts.pathType }}
        path: {{ .Values.ingress.hosts.path }}
        backend:
          service:
            name: {{ .Values.ingress.hosts.service.name }}
            port: 
              number: {{ .Values.ingress.hosts.service.port }}


#   tls: # < placing a host in the TLS config will determine what ends up in the cert's subjectAltNames
#     - hosts:
#       - nathancowsay.tk
#       secretName: crm-secret-tls

# ---

# apiVersion: v1
# kind: Secret
# metadata:
#   name: crm-secret-tls
# data:
#   tls.crt: cGVlcGVlcG9vcG9v
#   tls.key: cGVlcGVlcG9vcG9va2V5
# type: kubernetes.io/tls