apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storage.name }}
provisioner: {{ .Values.storage.provisioner }}
parameters:
  type: {{ .Values.storage.parameters.type }}
  fstype: {{ .Values.storage.parameters.fstype }}
  replication-type: {{ .Values.storage.parameters.replicationType }}